registered_users:
  - mail: muou1998@gmail.com
    user_name: cbblog
    password: cuibin7797A*
mask_rule:
  '*': "0123456789"
  '#': "0123456789"
  '¥': "0123456789"
  '@': "0123456789"
  '?': "0123456789"

mask_count_max: 2
interval_time_min: 2
interval_time_max: 5

filter_keywords:
  - "码"


reverse: false
show_progress_bar: false

dingding_notify_access_token: "4e678f5872a439578dfeb2870e095ab9"

#input_mask:
#  - "123456*1234*1234"
#  - "12345*12345*1234"

#proxy:
#  proxy.proxy302.com:2222:sFK6vpis:QuYEu6lJjT9dMezB
#  http: http://127.0.0.1:2080

img_ocr:
  app_key: "42388d723471988d"
  secret: "Iwe48GzINuVuh11npyTrGOk4bSpQwdvf"

